In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('movies_2.csv') # Gathering data

df.head(5)

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,1,Look Who's Talking,PG-13,7500000.0,296000000.0,1989-10-12,Romance,93.0,5.9,73638.0,"After a single, career-minded woman is left on..."
1,2,Driving Miss Daisy,PG,7500000.0,145793296.0,1989-12-13,Comedy,99.0,7.4,91075.0,An old Jewish woman and her African-American c...
2,3,Turner & Hooch,PG,13000000.0,71079915.0,1989-07-28,Crime,100.0,7.2,91415.0,"Det. Scott Turner (Tom Hanks) is an uptight, b..."
3,4,Born on the Fourth of July,R,14000000.0,161001698.0,1989-12-20,War,145.0,7.2,91415.0,The biography of Ron Kovic. Paralyzed in the V...
4,5,Field of Dreams,PG,15000000.0,84431625.0,1989-04-21,Drama,107.0,7.5,101702.0,"An Iowa corn farmer, hearing voices, interpret..."

In [3]:
# Assessing of data 

df.shape

df.isna()

,MovieID,Title,MPAA Rating,Budget,Gross,Release Date,Genre,Runtime,Rating,Rating Count,Summary
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
611,False,False,False,False,False,False,False,False,True,True,True
612,False,False,False,False,False,False,False,False,True,True,True
613,False,False,False,False,False,False,False,False,True,True,True
614,False,False,False,False,False,False,False,False,True,True,True
615,False,True,True,True,True,True,True,True,True,True,True

In [13]:
# Epic 3: Data Cleaning & Exploratory Data Analysis


newdf = df.drop("Summary", axis='columns')

print(newdf.head(5))

   MovieID                       Title MPAA Rating      Budget        Gross  \
0        1          Look Who's Talking       PG-13   7500000.0  296000000.0
1        2          Driving Miss Daisy          PG   7500000.0  145793296.0
2        3              Turner & Hooch          PG  13000000.0   71079915.0
3        4  Born on the Fourth of July           R  14000000.0  161001698.0
4        5             Field of Dreams          PG  15000000.0   84431625.0

  Release Date    Genre  Runtime  Rating  Rating Count
0   1989-10-12  Romance     93.0     5.9       73638.0
1   1989-12-13   Comedy     99.0     7.4       91075.0
2   1989-07-28    Crime    100.0     7.2       91415.0
3   1989-12-20      War    145.0     7.2       91415.0
4   1989-04-21    Drama    107.0     7.5      101702.0

In [14]:
# DataFrame RENAME

newdf = df.rename(columns={"MovieID": "movie_id", "Title": "title", "MPAA Rating": "mpaa_rating", "Budget": "budget", "Gross": "gross", "Release Date": "release_date" })


print(newdf.head(5))

   movie_id                       title mpaa_rating      budget        gross  \
0         1          Look Who's Talking       PG-13   7500000.0  296000000.0
1         2          Driving Miss Daisy          PG   7500000.0  145793296.0
2         3              Turner & Hooch          PG  13000000.0   71079915.0
3         4  Born on the Fourth of July           R  14000000.0  161001698.0
4         5             Field of Dreams          PG  15000000.0   84431625.0

  release_date    Genre  Runtime  Rating  Rating Count  \
0   1989-10-12  Romance     93.0     5.9       73638.0
1   1989-12-13   Comedy     99.0     7.4       91075.0
2   1989-07-28    Crime    100.0     7.2       91415.0
3   1989-12-20      War    145.0     7.2       91415.0
4   1989-04-21    Drama    107.0     7.5      101702.0

                                             Summary
0  After a single, career-minded woman is left on...
1  An old Jewish woman and her African-American c...
2  Det. Scott Turner (Tom Hanks) is an uptight, b...
3  The biography of Ron Kovic. Paralyzed in the V...
4  An Iowa corn farmer, hearing voices, interpret...